language: perl
sudo: false

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n
  - cpanm Alien::m4

env:
  - ALIEN_INSTALL_TYPE=share
  - ALIEN_INSTALL_TYPE=system

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.26"

script:
  - dzil test -v
